/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apitelegram;

/**
 *
 * @author Edo
 */
public class Grafica extends javax.swing.JFrame {

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Invia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Citta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        Invia.setText("jButton1");

        Citta.setColumns(20);
        Citta.setRows(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Invia)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(302, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Citta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Invia)
                .addContainerGap(193, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Citta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static String chiave="5130903459:AAHJ7stpGOH3ADTxyxAf88zu02VMpqXhUag";
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        threadTelegram t= new threadTelegram();
       t.start();
      ApiTelegram main = new ApiTelegram();
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Citta;
    private javax.swing.JButton Invia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
//private double distanza(double lat1, double lon1, double lat2, double lon2, String unit) {
//        if ((lat1 == lat2) && (lon1 == lon2)) {
//            return 0;
//        } else {
//            double theta = lon1 - lon2;
//            double dist = Math.sin(Math.toRadians(lat1)) * Math.sin(Math.toRadians(lat2)) + Math.cos(Math.toRadians(lat1)) * Math.cos(Math.toRadians(lat2)) * Math.cos(Math.toRadians(theta));
//            dist = Math.acos(dist);
//            dist = Math.toDegrees(dist);
//            dist = dist * 60 * 1.1515;
//            if (unit.equals("K")) {
//                dist = dist * 1.609344;
//            } else if (unit.equals("N")) {
//                dist = dist * 0.8684;
//            }
//            return (dist);
//        }
//    }

//   public List<datiPersona> leggiFile() throws FileNotFoundException, IOException {
//        BufferedReader reader;
//        List<datiPersona> n = new ArrayList<>();
//        
//        reader = new BufferedReader(new FileReader("salvaUtenti.csv"));
//        String line;
//        while ((line = reader.readLine()) != null) {
//            String[] split = line.split(";");
//            n.add(new datiPersona(split[0], split[1], split[2], split[3], split[4]));
//        }
//        
//        reader.close();
//        return n;
//    }

//private void Invia_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Invia_buttonActionPerformed
//        if (Citta_TextField.getText().equals("") || Citta_TextArea.getText().equals("")) {
//            JOptionPane.showMessageDialog(rootPane, "Errore, inserisci città o testo");
//        } else {
//            try {
//                OsmAPI leggi_coordinate = new OsmAPI();
//                System.out.println(leggi_coordinate.leggiXML(Citta_TextField.getText()));
//                List<datiPersona> dati = this.leggiFile();
//                
//                OsmAPI osm = new OsmAPI();
//                attributi a = osm.leggiXML(Citta_TextField.getText());
//                System.out.println("Size dati "+dati.size());
//                for (int i = 0; i < dati.size(); i++) {
//                    URL url;
//                    Scanner s;
//                    if (distanza(Double.parseDouble(dati.get(i).getLat()), Double.parseDouble(dati.get(i).getLon()),Double.parseDouble(a.getLat()), Double.parseDouble(a.getLon()), "K") <= 5) {
//                    System.out.println("KM "+distanza(Double.parseDouble(dati.get(i).getLat()), Double.parseDouble(dati.get(i).getLon()),Double.parseDouble(a.getLat()), Double.parseDouble(a.getLon()), "K"));
//                    System.out.println("CittaLon "+a.getLon());
//                    System.out.println("CittaLat "+a.getLat());
//                      System.out.println("CittaLonDati "+dati.get(i).getLon());
//                    System.out.println("CittaLatDati "+dati.get(i).getLat());
//                    System.out.println("*********************************");
//                    //if (Citta_TextField.getText().equals(dati.get(i).getCitta())) {
//                        url = new URL("https://api.telegram.org/bot" + chiave + "/sendMessage?chat_id=" + dati.get(i).getId() + "&text=" + Citta_TextArea.getText());
//                        System.out.println("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\");
//                        System.out.println("Chat id "+dati.get(i).getId());
//                        System.out.println("Testo "+Citta_TextArea.getText());
//                        System.out.println("\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\");
//                        s = new Scanner(url.openStream());
//                        s.next();
//                    }
//                }
//            } catch (IOException ex) {
//                Logger.getLogger(telegramMain.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (SAXException ex) {
//                Logger.getLogger(telegramMain.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ParserConfigurationException ex) {
//                Logger.getLogger(telegramMain.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            Citta_TextArea.setText("");
//            Citta_TextField.setText("");
//            
//        }